"""Sample tables

Revision ID: 10504b58949b
Revises: 
Create Date: 2018-08-13 15:07:31.873507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10504b58949b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('foo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foo_id'], ['foos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    op.drop_table('foos')
    # ### end Alembic commands ###
